services:
  - type: web
    name: hospital-management-system
    env: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rake assets:precompile db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hospital-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false  # You’ll manually add the master key in the Render dashboard

databases:
  - name: hospital-db
    databaseName: hospital_production
    user: hospital_user
