
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: Hospital_Data
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: localhost

development:
  <<: *default

test:
  <<: *default


production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: hospital_oydj
    username: <%= Rails.application.credentials.dig(:production, :database, :username) %>
    password: <%= Rails.application.credentials.dig(:production, :database, :password) %>
    host: dpg-d1ad23emcj7s73fdjtog-a
    port: 5432

  cache:
    <<: *primary_production

  queue:
    <<: *primary_production

  cable:
    <<: *primary_production

